### ISSUE TITLE
Where's the instructions how to build it?

### ISSUE THREAD

**Issue by ddbb2017** [mbikovitsky/WingDbg#1]
I'm trying to build it w/VS2015 and I'm getting a ton of errors. So far in the linked Deviare-InProc @ ef115d5 project:

1. These two are to start with:

```
1>..\Lib\libudis86\amalgamation.c(33): fatal error C1083: Cannot open include file: 'source\libudis86\decode.h': No such file or directory

2>LINK : fatal error LNK1181: cannot open input file '.......\WingDbg-master\Deviare-InProc\Libs\2015\NktHookLib64_Debug.lib'
```

2. Then all of these includes are missing from "WingDbg-master\Deviare-InProc\Src\Lib\libudis86\amalgamation.c"

```
#include "source\libudis86\decode.h"

#include "source\libudis86\extern.h"

#include "source\libudis86\syn.h"

#include "source\libudis86\types.h"

#include "source\libudis86\udint.h"
```

**Comment by mbikovitsky** [comment]
udis86 is a submodule in the Deviare-InProc repository. The missing files come from this submodule. Try running `git submodule update --init --recursive`.
